redis:
  log_driver: "none"
  image: redis
  expose:
    - "6379"

web:
  build: .
  command: ./gradlew run
  ports:
    - "4567:4567"
  expose:
    - "4567"
  links:
    - redis
  environment:
    PORT: "4567"
    FAKE_ENABLED: "true"
    REDISCLOUD_URL: "redis://redis:6379"

tests:
  build: .
  command: ./gradlew e2eTest
  links:
    - web
  environment:
    SERVER_TO_TEST: "web"
    PORT: "4567"

